# Generated by Django 3.1.4 on 2020-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_app', '0003_auto_20201223_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
